# Initializing the data

In [1]:
# DO NOT IMPORT PANDAS
### Lib imports
import tree as dt
import evaluation as ev
import numpy as np
import copy
import config as cfg
import cross_val as cv
import tree_plot as tp

In [2]:
data = np.loadtxt('noisy_dataset.txt')

In [3]:
best_hyper, F1_score, err_all_hyperparams, cm = cv.param_tuning(data, folds=10, test_percentage=0.1)

Running with hyperparameters: {'depth': 2, 'boundary': 2, 'prune': True}


/home/sacha/Bureau/Imperial/Intro_to_ML/decision_tree/evaluation.py:62: RuntimeWarning: invalid value encountered in double_scalars
  confusion_matrix[i, i] / np.sum(confusion_matrix[:, i]),


Running with hyperparameters: {'depth': 4, 'boundary': 2, 'prune': True}
Running with hyperparameters: {'depth': 6, 'boundary': 2, 'prune': True}
Running with hyperparameters: {'depth': 8, 'boundary': 2, 'prune': True}
Running with hyperparameters: {'depth': 10, 'boundary': 2, 'prune': True}
Running with hyperparameters: {'depth': 12, 'boundary': 2, 'prune': True}

Best averaged confusion matrix : 
 [[49.33333333  1.33333333  1.33333333  2.44444444]
 [ 2.         49.22222222  2.77777778  1.22222222]
 [ 2.22222222  2.22222222 50.66666667  2.11111111]
 [ 2.33333333  1.55555556  1.44444444 50.        ]]


In [ ]:
confusion_matrix = cm.copy()
recall_vect = np.zeros((1, cfg.NB_LABELS))
prec_vect = np.zeros((1, cfg.NB_LABELS))
classification_rate = np.zeros((1, cfg.NB_LABELS))
for i in range(confusion_matrix.shape[0]):

        recall_vect[0, i] = min(
            confusion_matrix[i, i] / np.sum(confusion_matrix[i, :]),
            confusion_matrix[i, i],
        )  # Recall = TP/(TP + FN)

        prec_vect[0, i] = min(
            confusion_matrix[i, i] / np.sum(confusion_matrix[:, i]),
            confusion_matrix[i, i],
        )  # Precision = TP/(TP + FP)

        classification_rate[0, i] = np.trace(confusion_matrix) / (
            np.trace(confusion_matrix)
            + np.sum(confusion_matrix[:, i])
            + np.sum(confusion_matrix[i, :])
            - 2 * confusion_matrix[i, i]
        )  # Classification rate = (TP + TN)/(TP + TN + FP + FN)
        
uar = np.mean(recall_vect)  # Unweighted Average Recall
uap = np.mean(prec_vect)  # Unweighted Average Precision
f1 = 2 * (uar * uap) / (uar + uap)  # Compute F1
uac = np.mean(classification_rate)  # Unweighted Averate Classification Rate

In [ ]:
recall_vect[0]

In [ ]:
prec_vect

In [ ]:
classification_rate

In [ ]:
f2 = []
for i in range(recall_vect.shape[1]):
    f2.append(2*(recall_vect[0,i] * prec_vect[0,i])/(recall_vect[0,i] + prec_vect[0,i]))

In [ ]:
f1

In [ ]:
f2 = np.mean(f2)

In [ ]:
f2

In [ ]:
tree = tp.final_plot(best_hyper, data= "noisy_dataset")

In [ ]:

correct = 0
data = np.loadtxt('noisy_dataset.txt')
for i in range(data.shape[0]):
    if ev.predict(tree, data[i,:]) == data[i,-1]:
        correct +=1
print(correct/i)
